import type { Metadata } from "next";
import localFont from "next/font/local";
import './globals.css'
import AOSWrapper from "../components/AOSWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: " TopTea Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children,
 }: Readonly<{
  children: React.ReactNode;
 }>)
{
  return (
    <html lang="en"
    data-aos="fade-right" 
data-aos-duration="1500"
data-aos-delay="200"
>


      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AOSWrapper />
        {children}
        
      </body>
    </html>
  );
}
